name: ST Tools Build

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Select the project to build'
        required: true
        default: 'scribbledom'
        type: choice
        options:
          - scribbledom
          - staig
          - deepst
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Clears disk space.
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo apt-get clean

      - name: Prepare Image Metadata
        id: prep
        run: |
          OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}
          PROJECT=${{ github.event.inputs.project }}
          TAG=${{ github.event.inputs.tag }}
          
          # GHCR: ghcr.io/tawhidmm/staig:latest
          echo "ghcr_tag=ghcr.io/${OWNER_LC}/${PROJECT}:${TAG}" >> $GITHUB_OUTPUT
          
          # Docker Hub: tawhidmm/st_tools:staig-latest
          echo "dh_tag=${{ secrets.DOCKERHUB_USERNAME }}/st_tools:${PROJECT}-${TAG}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Targets the specific tool folder (staig, deepst, etc.)
          context: ./${{ github.event.inputs.project }}
          file: ./${{ github.event.inputs.project }}/Dockerfile
          push: true
          tags: |
            ${{ steps.prep.outputs.ghcr_tag }}
            ${{ steps.prep.outputs.dh_tag }}
          # Caching is vital for these 12GB+ builds
          cache-from: type=gha
          cache-to: type=gha,mode=max